services:
  gitlab:
    image:
      gitlab/gitlab-ee:17.7.4-ee.0
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      GITLAB OMNIBUS_CONFIG:|
        # Add any other gitlab.rb configuration here, each on its own line external_url 'http://10.1.0.124'
    ports: -'80:80'
volumes:
- '$GITLAB_HOME/config:/etc/gitlab' 
- '$GITLAB_HOME/logs:/var/log/gitlab' 
- '$GITLAB_HOME/data:/var/opt/gitlab' 
shm_size: '256m'